### ISSUE TITLE
Container does not start after rebuild

### ISSUE THREAD

**Issue by sgofferj** [SamR1/docker-fittrackee#14]
Unfortunately, the weekend release doesn't seem to have fixed my issue. And without any error output from the container, I'm somewhat fishing in the dark, trying to find the problem.

```
┌─[root@nostromo][/storage/docker/docker-fittrackee]
└──▪ make rebuild
Building fittrackee
Sending build context to Docker daemon  207.4kB
Step 1/16 : FROM python:3.9
 ---> 5b3b4504ff1f
Step 2/16 : MAINTAINER SamR1@users.noreply.github.com
 ---> Running in 70add47dd3e5
Removing intermediate container 70add47dd3e5
 ---> d0fe312a8454
Step 3/16 : RUN mkdir -p /usr/src/app
 ---> Running in 464e68ab17a8
Removing intermediate container 464e68ab17a8
 ---> 1f50294f3a30
Step 4/16 : WORKDIR /usr/src/app
 ---> Running in bc4121bd3d64
Removing intermediate container bc4121bd3d64
 ---> 51fea107ec7e
Step 5/16 : COPY scripts/ /usr/src/app/scripts
 ---> 378086a070ca
Step 6/16 : COPY .env /usr/src/app
 ---> adc751e80731
Step 7/16 : RUN pip install --upgrade pip
 ---> Running in 2a17c2bfe3ba
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.1.2)
Collecting pip
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.2
    Uninstalling pip-21.1.2:
      Successfully uninstalled pip-21.1.2
Successfully installed pip-21.1.3
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
Removing intermediate container 2a17c2bfe3ba
 ---> 4e2b727c8a74
Step 8/16 : RUN pip install SQLAlchemy==1.4.7 fittrackee
 ---> Running in ced8da3babc4
Collecting SQLAlchemy==1.4.7
  Downloading SQLAlchemy-1.4.7-cp39-cp39-manylinux2014_x86_64.whl (1.5 MB)
Collecting fittrackee
  Downloading fittrackee-0.4.8-py3-none-any.whl (1.7 MB)
Collecting greenlet!=0.4.17
  Downloading greenlet-1.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (162 kB)
Collecting flask-migrate<4.0,>=3.0
  Downloading Flask_Migrate-3.0.1-py2.py3-none-any.whl (12 kB)
Collecting humanize<4.0.0,>=3.5.0
  Downloading humanize-3.9.0-py3-none-any.whl (84 kB)
Collecting flask<3.0,>=2.0
  Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
Collecting pyjwt<3.0,>=2.1
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting flask-bcrypt<0.8.0,>=0.7.1
  Downloading Flask-Bcrypt-0.7.1.tar.gz (5.1 kB)
Collecting flask-dramatiq<0.7.0,>=0.6.0
  Downloading flask_dramatiq-0.6.0-py3-none-any.whl (5.9 kB)
Collecting psycopg2-binary<3.0,>=2.9
  Downloading psycopg2_binary-2.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
Collecting tqdm<5.0,>=4.61
  Downloading tqdm-4.61.1-py2.py3-none-any.whl (75 kB)
Collecting python-forecastio<2.0,>=1.4
  Downloading python-forecastio-1.4.0.tar.gz (7.2 kB)
Collecting dramatiq[redis]<2.0.0,>=1.10.0
  Downloading dramatiq-1.11.0-py3-none-any.whl (112 kB)
Collecting gunicorn<21.0,>=20.1
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting gpxpy==1.3.4
  Downloading gpxpy-1.3.4.tar.gz (105 kB)
Collecting staticmap<0.6.0,>=0.5.4
  Downloading staticmap-0.5.5.tar.gz (5.6 kB)
Collecting fittrackee
  Downloading fittrackee-0.4.7-py3-none-any.whl (1.9 MB)
Collecting flask<2.0,>=1.1
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
Collecting flask-migrate<3.0,>=2.7
  Downloading Flask_Migrate-2.7.0-py2.py3-none-any.whl (13 kB)
Collecting pytz<2022.0,>=2021.1
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting shortuuid<2.0.0,>=1.0.1
  Downloading shortuuid-1.0.1-py3-none-any.whl (7.5 kB)
Collecting prometheus-client>=0.2
  Downloading prometheus_client-0.11.0-py2.py3-none-any.whl (56 kB)
Collecting redis<4.0,>=2.0
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting Werkzeug<2.0,>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting itsdangerous<2.0,>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2<3.0,>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting click<8.0,>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting bcrypt
  Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
Collecting Flask-SQLAlchemy>=1.0
  Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Collecting alembic>=0.7
  Downloading alembic-1.6.5-py2.py3-none-any.whl (164 kB)
Collecting python-editor>=0.3
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting Mako
  Downloading Mako-1.1.4-py2.py3-none-any.whl (75 kB)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn<21.0,>=20.1->fittrackee) (57.0.0)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-2.0.1-cp39-cp39-manylinux2010_x86_64.whl (30 kB)
Collecting requests>=1.6
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting responses
  Downloading responses-0.13.3-py2.py3-none-any.whl (25 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting Pillow
  Downloading Pillow-8.3.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
Collecting cffi>=1.1
  Downloading cffi-1.14.5-cp39-cp39-manylinux1_x86_64.whl (406 kB)
Collecting six>=1.4.1
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: gpxpy, flask-bcrypt, python-forecastio, staticmap
  Building wheel for gpxpy (setup.py): started
  Building wheel for gpxpy (setup.py): finished with status 'done'
  Created wheel for gpxpy: filename=gpxpy-1.3.4-py3-none-any.whl size=40009 sha256=d155e788a023e1efd7d41f8ee2f30bd3f24bbdbbe69b9f1a78c8563ca74e3803
  Stored in directory: /root/.cache/pip/wheels/49/34/75/4f64882dbdfe9420686cbf13469dbe0fdeb1e8389ea4a0a8c4
  Building wheel for flask-bcrypt (setup.py): started
  Building wheel for flask-bcrypt (setup.py): finished with status 'done'
  Created wheel for flask-bcrypt: filename=Flask_Bcrypt-0.7.1-py3-none-any.whl size=5031 sha256=30a3a2a6d2fd8e9a40aca48c1c7870a49991cae9f0cf070ca52694b628e64d40
  Stored in directory: /root/.cache/pip/wheels/46/c7/4d/b94ab085c8bb76ffcb87b41efbe5919f59292134b018fa0d57
  Building wheel for python-forecastio (setup.py): started
  Building wheel for python-forecastio (setup.py): finished with status 'done'
  Created wheel for python-forecastio: filename=python_forecastio-1.4.0-py3-none-any.whl size=7742 sha256=3cf72fde4052d3f885189499791e9fd844c8ed9ba550152bb801247154b25614
  Stored in directory: /root/.cache/pip/wheels/59/53/93/6599f6be21ffc08522d80d3bfa7e7c917bbe1d0c789ae4e9ac
  Building wheel for staticmap (setup.py): started
  Building wheel for staticmap (setup.py): finished with status 'done'
  Created wheel for staticmap: filename=staticmap-0.5.5-py3-none-any.whl size=6460 sha256=a649e1dd717c4427ca0296ed95146295cb8b6f96cb7cb46419eb109b220aca21
  Stored in directory: /root/.cache/pip/wheels/e1/08/b0/0017fb0adf40a83e740cf2342adbb112ed92ec52cf7c825a1a
Successfully built gpxpy flask-bcrypt python-forecastio staticmap
Installing collected packages: MarkupSafe, Werkzeug, urllib3, six, pycparser, Jinja2, itsdangerous, idna, greenlet, click, chardet, certifi, SQLAlchemy, requests, python-editor, python-dateutil, prometheus-client, Mako, flask, cffi, responses, redis, Pillow, Flask-SQLAlchemy, dramatiq, bcrypt, alembic, tqdm, staticmap, shortuuid, pytz, python-forecastio, pyjwt, psycopg2-binary, humanize, gunicorn, gpxpy, flask-migrate, flask-dramatiq, flask-bcrypt, fittrackee
Successfully installed Flask-SQLAlchemy-2.5.1 Jinja2-2.11.3 Mako-1.1.4 MarkupSafe-2.0.1 Pillow-8.3.0 SQLAlchemy-1.4.7 Werkzeug-1.0.1 alembic-1.6.5 bcrypt-3.2.0 certifi-2021.5.30 cffi-1.14.5 chardet-4.0.0 click-7.1.2 dramatiq-1.11.0 fittrackee-0.4.7 flask-1.1.4 flask-bcrypt-0.7.1 flask-dramatiq-0.6.0 flask-migrate-2.7.0 gpxpy-1.3.4 greenlet-1.1.0 gunicorn-20.1.0 humanize-3.9.0 idna-2.10 itsdangerous-1.1.0 prometheus-client-0.11.0 psycopg2-binary-2.9.1 pycparser-2.20 pyjwt-2.1.0 python-dateutil-2.8.1 python-editor-1.0.4 python-forecastio-1.4.0 pytz-2021.1 redis-3.5.3 requests-2.25.1 responses-0.13.3 shortuuid-1.0.1 six-1.16.0 staticmap-0.5.5 tqdm-4.61.1 urllib3-1.26.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container ced8da3babc4
 ---> 6e1bfb22359f
Step 9/16 : CMD mkdir $UPLOAD_FOLDER
 ---> Running in bf2c1c53c2d4
Removing intermediate container bf2c1c53c2d4
 ---> 2c74aae00d49
Step 10/16 : ARG HOST
 ---> Running in 58c868b38ae1
Removing intermediate container 58c868b38ae1
 ---> 0e51b06df0b2
Step 11/16 : ARG PORT
 ---> Running in d9d14f343c31
Removing intermediate container d9d14f343c31
 ---> e2ae3be2dfda
Step 12/16 : ARG APP_WORKERS
 ---> Running in 74c71d685948
Removing intermediate container 74c71d685948
 ---> 874e068263b8
Step 13/16 : ARG GUNICORN_TIMEOUT
 ---> Running in ba77a9b9824e
Removing intermediate container ba77a9b9824e
 ---> 30b11046b896
Step 14/16 : ARG GUNICORN_LOG
 ---> Running in 6c0d1e811a5b
Removing intermediate container 6c0d1e811a5b
 ---> ffd920c88fca
Step 15/16 : ARG GUNICORN_THREADS
 ---> Running in bea0e03ccd43
Removing intermediate container bea0e03ccd43
 ---> 1c80cccd13e1
Step 16/16 : CMD gunicorn -b $HOST:$PORT "fittrackee:create_app()" --error-logfile $GUNICORN_LOG --timeout $GUNICORN_TIMEOUT --workers=$APP_WORKERS --threads=$GUNICORN_THREADS --worker-class=gthread
 ---> Running in d08e996ad74e
Removing intermediate container d08e996ad74e
 ---> d6d5e2662432
Successfully built d6d5e2662432
Successfully tagged docker-fittrackee_fittrackee:latest
```

```
┌─[root@nostromo][/storage/docker/docker-fittrackee]
└──▪ docker-compose up
Recreating fittrackee ... done
Attaching to fittrackee
fittrackee exited with code 3
```

**Comment by SamR1** [comment]
argh :(

are the needed environment variables exposed (especially database ones)?

I don't know if it's the same issue, but one way to reproduce the startup error with code 3 is to start container with missing env variables (for instance using `docker-compose up` directly instead of `make up/run` that exposes needed env variables) : 

```
 12:54:20  sam@sam-p64kv7  ...Devs/00_Perso/docker-fittrackee  ⬡ v16.3.0   main ✔ 
$ make rebuild
redis uses an image, skipping
Building fittrackee-db
(...)
Successfully tagged docker-fittrackee_fittrackee-db:latest
Building fittrackee
(...)
Successfully tagged docker-fittrackee_fittrackee:latest

 12:55:19  sam@sam-p64kv7  ...Devs/00_Perso/docker-fittrackee  ⬡ v16.3.0   main ✔  55s 
$ docker-compose up                                           
Creating fittrackee-redis ... done
Creating fittrackee-db    ... done
Creating fittrackee       ... done
Attaching to fittrackee-redis, fittrackee-db, fittrackee
(...)
fittrackee exited with code 3
^CGracefully stopping... (press Ctrl+C again to force)
Stopping fittrackee-redis ... done
Stopping fittrackee-db    ... done

 13:00:17  sam@sam-p64kv7  ...Devs/00_Perso/docker-fittrackee  ⬡ v16.3.0   main ✔  6s 
$ make run
Starting fittrackee-redis ... done
Starting fittrackee-db    ... done
Starting fittrackee       ... done

 13:00:41  sam@sam-p64kv7  ...Devs/00_Perso/docker-fittrackee  ⬡ v16.3.0   main ✔ 
$ docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS         PORTS                                       NAMES
6a8aa8c7dc32   docker-fittrackee_fittrackee      "/bin/sh -c '$VIRTUA…"   31 seconds ago   Up 2 seconds   0.0.0.0:5020->5000/tcp, :::5020->5000/tcp   fittrackee
9a8cd11ea986   redis:latest                      "docker-entrypoint.s…"   32 seconds ago   Up 2 seconds   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp   fittrackee-redis
a2c29f04e781   docker-fittrackee_fittrackee-db   "docker-entrypoint.s…"   32 seconds ago   Up 2 seconds   5432/tcp                                    fittrackee-db
``` 

In addition, can you try with the last version Dockerfile (I made some fixes this week end, including [FitTrackee installation in a virtual env](https://github.com/SamR1/docker-fittrackee/issues/10)). I'm not sure that will fix your issue, but the install will be more clean.

**Comment by sgofferj** [comment]
No, no joy. Neither with ```make up```. By the way, shouldn't it be enough to include .env in docker-compose.yml?

In any case, here are all my relevant files:

docker-compose.yml
```yaml
version: '3.8'

services:
  fittrackee:
    container_name: fittrackee
    build: .
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    volumes:
      - /storage/docker/fittrackee/data:/uploads:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fitt-service.loadbalancer.server.port=5000"
      - "traefik.docker.network=web_services"
      - "traefik.http.routers.fittrackee.entrypoints=web"
      - "traefik.http.routers.fittrackee.rule=Host(`fittrackee.gofferje.net`)"
      - "traefik.http.routers.fittrackee.middlewares=redirect@file"
      - "traefik.http.routers.fittrackee-secure.entrypoints=websecure"
      - "traefik.http.routers.fittrackee-secure.rule=Host(`fittrackee.gofferje.net`)"
      - "traefik.http.routers.fittrackee-secure.tls=true"
      - "traefik.http.routers.fittrackee-secure.tls.domains[0].main=fittrackee.gofferje.net"
      - "traefik.http.routers.fittrackee-secure.middlewares=hsts@file"
      - "traefik.http.routers.fittrackee-secure.service=fitt-service"

networks:
  default:
    external:
      name: web_services
```

Dockerfile:
```dockerfile
FROM python:3.9

MAINTAINER SamR1@users.noreply.github.com

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# copy needed files
COPY scripts/ /usr/src/app/scripts
COPY .env /usr/src/app

# install fittrackee from pip
ENV VIRTUAL_ENV=/usr/src/app/.venv
RUN python3 -m venv $VIRTUAL_ENV
RUN $VIRTUAL_ENV/bin/pip install --upgrade pip setuptools wheel
RUN $VIRTUAL_ENV/bin/pip install fittrackee

# create uploads folder
CMD mkdir -p $UPLOAD_FOLDER

# environment variables
ARG APP_WORKERS
ARG GUNICORN_TIMEOUT
ARG GUNICORN_LOG
ARG GUNICORN_THREADS

# run fittrackee server w/ gunicorn
CMD $VIRTUAL_ENV/bin/gunicorn -b 0.0.0.0:5000 "fittrackee:create_app()" --error-logfile $GUNICORN_LOG --timeout $GUNICORN_TIMEOUT --workers=$APP_WORKERS --threads=$GUNICORN_THREADS --worker-class=gthread
```

.env:
```bash
# Custom variables initialisation

# Application
export FLASK_APP=fittrackee
export HOST=0.0.0.0
export PORT=5000
export APP_SETTINGS=fittrackee.config.ProductionConfig
export APP_SECRET_KEY='xxxxxxxxx'
export APP_LOG=fittrackee.log
export UPLOAD_FOLDER=/uploads

export APP_WORKERS=2
export GUNICORN_LOG=gunicorn.log
export GUNICORN_TIMEOUT=300
export GUNICORN_THREADS=4

# Database
export DATABASE_URL=postgres://fittrackee:fittrackee@xxx.xxx.xxx.xxx:5432/fittrackee
#export DATABASE_DISABLE_POOLING=

# Emails
export UI_URL=https://fittrackee.gofferje.net
export EMAIL_URL=smtp://none:none@xxx.xxxxxxxx.xxx:25
export SENDER_EMAIL=xxxxxxxxxx@xxxxxxxx.xxx
export REDIS_URL=redis://redis:6379
export WORKERS_PROCESSES=2

# Activities
#export TILE_SERVER_URL=
#export MAP_ATTRIBUTION=
#export WEATHER_API_KEY=
```

A few notes: I have a central PGDB and a central redis. Both should be reachable from the container - at least it worked before I tried the update.

Is there any way to get fittrackee to tell on STDOUT what it doesn't like?

**Comment by SamR1** [comment]
I thought that too for .env but maybe I'm missing something...

There are 2 logs files (see `APP_LOG` and `GUNICORN_LOG` env vars).
By default, there are both located in **fittrackee** container (which does not make debugging easy when the container does not start...). Maybe they should be located in a external volume.

FitTrackee needs to connect to database to start (otherwise an error will be displayed in gunicorn logs). Can you check if the database is reachable?

**Comment by sgofferj** [comment]
No prob, just bind-mounting an extra directory where the logs go. fittrackee.log is empty, gunicorn.log not so much...
I never liked python... One of the main reasons was and is this Java-like endless error messages... But it seems, something is missing?

```log
┌─[root@nostromo][/storage/docker/fittrackee/log]
└──▪ cat gunicorn.log 
[2021-07-06 15:08:54 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2021-07-06 15:08:54 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2021-07-06 15:08:54 +0000] [7] [INFO] Using worker: gthread
[2021-07-06 15:08:54 +0000] [8] [INFO] Booting worker with pid: 8
[2021-07-06 15:08:54 +0000] [9] [INFO] Booting worker with pid: 9
[2021-07-06 15:08:55 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 59, in create_app
    if db.engine.dialect.has_table(db.engine.connect(), 'app_config'):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
[2021-07-06 15:08:55 +0000] [8] [INFO] Worker exiting (pid: 8)
[2021-07-06 15:08:55 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 59, in create_app
    if db.engine.dialect.has_table(db.engine.connect(), 'app_config'):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
[2021-07-06 15:08:55 +0000] [9] [INFO] Worker exiting (pid: 9)
[2021-07-06 15:08:55 +0000] [7] [WARNING] Worker with pid 9 was terminated due to signal 15
[2021-07-06 15:08:55 +0000] [7] [INFO] Shutting down: Master
[2021-07-06 15:08:55 +0000] [7] [INFO] Reason: Worker failed to boot.
```

**Comment by SamR1** [comment]
Thanks for the logs.

I missed it, sorry :/, but the engine URL is not right in DATABASE_URL env var (see [release notes for v0.4.7](https://github.com/SamR1/FitTrackee/releases/tag/v0.4.7)): 
```
export DATABASE_URL=postgres://fittrackee:fittrackee@xxx.xxx.xxx.xxx:5432/fittrackee
```

It should be:
```
export DATABASE_URL=postgresql://fittrackee:fittrackee@xxx.xxx.xxx.xxx:5432/fittrackee
```

**Comment by sgofferj** [comment]
And that was the problem :). Thanks a lot and sorry for missing the release notes!

**Comment by SamR1** [comment]
no worry :)
