### ISSUE TITLE
no docker container created

### ISSUE THREAD

**Issue by kajdo** [SamR1/docker-fittrackee#18]
Hi,

i followed the description, but no docker container was created, `make build run init` also finished without any issues, but `sudo docker ps -a` doesn't show a newly created fittrackee container

**Edit 1:** ok i missed that `docker-compose up` is necessary - maybe that should be mentioned in the readme as well

After `docker-compose up`, there are 2 containers (redis + db) but the 3rd one is still not showing up - ps see below compose up output:
```
Creating network "docker-fittrackee_default" with the default driver
Creating volume "docker-fittrackee_fittrackee_upload" with default driver
Pulling redis (redis:latest)...
latest: Pulling from library/redis
7d63c13d9b9b: Already exists
a2c3b174c5ad: Pull complete
283a10257b0f: Pull complete
7a08c63a873a: Pull complete
0531663a7f55: Pull complete
9bf50efb265c: Pull complete
Digest: sha256:a89cb097693dd354de598d279c304a1c73ee550fbfff6d9ee515568e0c749cfe
Status: Downloaded newer image for redis:latest
Creating fittrackee-db ...
Creating fittrackee-redis ...
Killed
```
could you pls advise what should be checked as a next step?

**Comment by SamR1** [comment]
Hi,

Normally, there is no need to run an additional `docker-compose up` ([`make run`](https://github.com/SamR1/docker-fittrackee/blob/main/Makefile#L27) runs it).

Can you check that the needed environment variables are not empty in `.env`? If one is missing, `fittrackee` container can not start.  
is there an error in FitTrackee logs?

**Comment by kajdo** [comment]
Hi,

thx for the reply.

`make run` did definitely not run docker-compose up ... do not know about makefiles, so I can just tell that it didn't run because there wasn't a docker created - checked via `docker ps -a` and portainer

checking the `.env` file leaves me with:
```
# Custom variables initialisation

# Host directory to store FitTrackee logs
export FITTRACKEE_LOG_DIR=./log

# Application
export FLASK_APP=fittrackee
export PORT=5000
export APP_SETTINGS=fittrackee.config.ProductionConfig
export APP_SECRET_KEY='please change me'
export APP_LOG=/logs/fittrackee.log
export UPLOAD_FOLDER=/uploads
# gunicorn settings
# see https://docs.gunicorn.org/en/stable/settings.html#worker-processes
export APP_WORKERS=2
export GUNICORN_LOG=/logs/gunicorn.log
export GUNICORN_TIMEOUT=300
export GUNICORN_THREADS=4

# Database
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export DATABASE_URL=postgresql://fittrackee:fittrackee@fittrackee-db:5432/fittrackee
#export DATABASE_DISABLE_POOLING=

# Emails
export UI_URL=
export EMAIL_URL=
export SENDER_EMAIL=
export REDIS_URL=redis://redis:6379
export WORKERS_PROCESSES=2

# Activities
#export TILE_SERVER_URL=
#export MAP_ATTRIBUTION=
#export WEATHER_API_KEY=
```

I basically left the `.env ` as it is because for my first test 
- I thought I don't need email specific settings, 
- the Acvivities are commented out - so I didn't bother either,
- running it locally I didn't care about the app secret key either (just testing)
- **_only change I did_** -- export FITTRACKEE_LOG_DIR=./log

> hat the needed environment variables
I checked [your installation guide](https://samr1.github.io/FitTrackee/installation.html) which says: "not all mandatory depending on deployment method.". But I didn't find a way to figure out which are mandatory for which deployment method.

I'd really love to have a look at fittrackee - but currently I'm a bit helpless :(

> is there an error in FitTrackee logs?
fittrackee.log is empty (the one which is in the directory where I git cloned fittrackee and did the make commands)
gunicorn.log gives me following:

```
[2021-11-07 15:46:15 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2021-11-07 15:46:15 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2021-11-07 15:46:15 +0000] [7] [INFO] Using worker: gthread
[2021-11-07 15:46:15 +0000] [8] [INFO] Booting worker with pid: 8
[2021-11-07 15:46:15 +0000] [9] [INFO] Booting worker with pid: 9
[2021-11-07 15:51:04 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 50, in create_app
    email_service.init_email(app)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/emails/email.py", line 83, in init_email
    parsed_url = parse_email_url(app.config['EMAIL_URL'])
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/emails/utils_email.py", line 11, in parse_email_url
    raise InvalidEmailUrlScheme()
fittrackee.emails.exceptions.InvalidEmailUrlScheme
[2021-11-07 15:51:04 +0000] [9] [INFO] Worker exiting (pid: 9)
[2021-11-07 15:51:04 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 50, in create_app
    email_service.init_email(app)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/emails/email.py", line 83, in init_email
    parsed_url = parse_email_url(app.config['EMAIL_URL'])
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/emails/utils_email.py", line 11, in parse_email_url
    raise InvalidEmailUrlScheme()
fittrackee.emails.exceptions.InvalidEmailUrlScheme
[2021-11-07 15:51:04 +0000] [8] [INFO] Worker exiting (pid: 8)
[2021-11-07 15:51:35 +0000] [7] [INFO] Shutting down: Master
[2021-11-07 15:51:35 +0000] [7] [INFO] Reason: Worker failed to boot.
```
now I'm not sure about if the email env variables can stay empty - will try to fill them out and give it another shot

**Comment by SamR1** [comment]
Thanks for the logs.

`EMAIL_URL` is empty, so **FitTrackee** can not start.

If you want to evaluate **FitTrackee** first, you can use `docker-compose-dev.yml` file from **FitTrackee** repo ([FitTrackee/installation.html#docker](https://samr1.github.io/FitTrackee/installation.html#docker)), all variables are filled in.

**Comment by SamR1** [comment]
Alternatively, you can just use the same `EMAIL_URL` as in `docker-compose-dev.yml`:  
```
export EMAIL_URL=smtp://none:none@mail:1025
```

**Comment by kajdo** [comment]
will give it a shot with your second option .... `export EMAIL_URL=smtp://none:none@mail:1025`

tried it with a gmail smtp url - but gmail is anyhow a bit a pain using it with smtp .... just ran into a timeout, so I sized the VM a bit bigger .... 

will put in your dev EMAIL_URL after resizing and start over with `make build run init`

**Comment by kajdo** [comment]
hmpf ... sad

got excited because of:
```
Creating fittrackee-redis ... done
Creating fittrackee-db    ... done
Creating fittrackee       ... done
```
so - `make build run init` did in fact create the 3 docker containers

but I got an exhausting traceback
```
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "fittrackee-db" (172.23.0.3) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/.venv/bin/fittrackee_upgrade_db", line 5, in <module>
    from fittrackee.__main__ import upgrade_db
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/__main__.py", line 23, in <module>
    app = create_app()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 59, in create_app
    if db.engine.dialect.has_table(db.engine.connect(), 'app_config'):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3165, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3244, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3214, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "fittrackee-db" (172.23.0.3) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/14/e3q8)
make: *** [Makefile:16: migrate] Error 137
```
redis and db are running, fittrackee is stopped

just out of curiosity i tried to start the fittrackee container manually via portainer and got following log:
```
Traceback (most recent call last):,
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run,
    self.sleep(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep,
    ready = select.select([self.PIPE[0]], [], [], 1.0),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld,
    self.reap_workers(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers,
    raise HaltServer(reason, self.WORKER_BOOT_ERROR),
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 642, in kill_worker,
    os.kill(pid, sig),
ProcessLookupError: [Errno 3] No such process,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/src/app/.venv/bin/gunicorn", line 8, in <module>,
    sys.exit(run()),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run,
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run,
    super().run(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run,
    Arbiter(self).run(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run,
    self.halt(reason=inst.reason, exit_status=inst.exit_status),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt,
    self.stop(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 390, in stop,
    self.kill_workers(sig),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 632, in kill_workers,
    self.kill_worker(pid, sig),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 642, in kill_worker,
    os.kill(pid, sig),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld,
    self.reap_workers(),
  File "/usr/src/app/.venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers,
    raise HaltServer(reason, self.WORKER_BOOT_ERROR),
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>,
```

**Comment by kajdo** [comment]
the ip address shown is none of mine
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "fittrackee-db" (172.23.0.3) and accepting
	TCP/IP connections on port 5432?
```
it's not in my .env file - so I'm not sure if it's something i did wrong

**_EDIT_**
the IP is assigned via docker to fittrackee-db - so it should be OK
fittrackee-db is running

**_EDIT2_**
fittrackee:5000 gives me a login screen, but with red note about an error
trying to login with the admin credentials gives me an error as well
`An error occurred. Please contact the administrator.`

**Comment by kajdo** [comment]
I just tried to track down the issue a bit, so I
- deleted fittrackee.log + gunicorn.log
- stopped all containers
- started redis and db container --> running
- started fittrackee container --> running
- checked fittrackee:5000 --> login screen with above error `application: An error occurred. Please contact the administrator.`
- checked logs --> something wrong with the db ... 

gunicorn.log looking good imho
```
[2021-11-07 20:17:00 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2021-11-07 20:17:00 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2021-11-07 20:17:00 +0000] [7] [INFO] Using worker: gthread
[2021-11-07 20:17:00 +0000] [8] [INFO] Booting worker with pid: 8
[2021-11-07 20:17:00 +0000] [9] [INFO] Booting worker with pid: 9
```

fittrackee.log
```
2021/11/07 20:18:12 - fittrackee - ERROR - Exception on /api/config [GET]
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "app_config" does not exist
LINE 2: FROM app_config
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/fittrackee/application/app_config.py", line 56, in get_application_config
    config = AppConfig.query.one()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2806, in one
    return self._iter().one()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2844, in _iter
    result = self.session.execute(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "app_config" does not exist
LINE 2: FROM app_config
             ^

[SQL: SELECT app_config.id AS app_config_id, app_config.max_users AS app_config_max_users, app_config.gpx_limit_import AS app_config_gpx_limit_import, app_config.max_single_file_size AS app_config_max_single_file
_size, app_config.max_zip_file_size AS app_config_max_zip_file_size
FROM app_config]
```

**Comment by kajdo** [comment]
not sure if it was because of that - but I started all over again and followed your very first tip (https://samr1.github.io/FitTrackee/installation.html#docker)

guess beside the setup issues I had with this repo - the main problem might have been, that my vm run out of space

long story short - its working

happy that i can play around with it and try it out 

thx for your responses - good to see that you react on issues

I suggest to close this issue, because most likely the main issue was that somewhen my machine just run out of space and understandibly that might have caused some unpredictable issues

**Comment by SamR1** [comment]
thanks for your feedback, glad it's now working :)
